[package]
name = "common"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[lints]
workspace = true

[dependencies]
rustix = { version = "1.1", default-features = false, features = [
  "alloc",
  "fs",
  "net",
  "mm",
  "shm",
  "stdio",
  "param",
  "process",
  "termios",
  "thread",
  "time",
] }
[target.'cfg(any(target_arch = "aarch64", target_arch = "x86_64", target_arch = "x86"))'.dependencies]
cpufeatures = { version = "0.3" }

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
fastrand = { version = "2.4", default-features = false, features = [ "std" ] }
